#!/usr/bin/env bash

./getem.1 mainnet apps
./getem.1 mainnet logs
./getem.1 mainnet neighbors
./getem.1 mainnet statements
./getem.1 mainnet txs
# ./getem.1 mainnet combined
# ./getem.1 mainnet raw
# ./getem.1 mainnet zips

./getem.1 gnosis apps
./getem.1 gnosis logs
./getem.1 gnosis neighbors
./getem.1 gnosis statements
./getem.1 gnosis txs
# ./getem.1 gnosis combined
# ./getem.1 gnosis raw
# ./getem.1 gnosis zips
